// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQotZ1UzKoGEhAeVW6PcA6t1AefPaKxTA',
    appId: '1:81680579881:web:59dc5451f0227d83e70b38',
    messagingSenderId: '81680579881',
    projectId: 'nutriscan-f3e75',
    authDomain: 'nutriscan-f3e75.firebaseapp.com',
    storageBucket: 'nutriscan-f3e75.appspot.com',
    measurementId: 'G-N2QYC5CV02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAD2tW6pl5YdOt_REw1ge0fHOXux_2B0',
    appId: '1:81680579881:android:3e84f99b872f7a5ee70b38',
    messagingSenderId: '81680579881',
    projectId: 'nutriscan-f3e75',
    storageBucket: 'nutriscan-f3e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJAV_n9ecD9JVOZwzhLSVkwRJWQIv2SU',
    appId: '1:81680579881:ios:153f48107b4fbce0e70b38',
    messagingSenderId: '81680579881',
    projectId: 'nutriscan-f3e75',
    storageBucket: 'nutriscan-f3e75.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );
}
